### PR TITLE
fix keys_path to not implicitly include a '/'

### LINKED ISSUE #22: keys_path shouldn't have an implicit '/'
Changing keys_path: 'dir' assumes that dir will have a '/' separator

### PR DESCRIPTION
**Pull request by nwmcsween**
fixes #22

### CODE REVIEW

**Comment by felixfontein** [comment]
Thanks for creating a PR! While this should work fine in general for Linux and friends (https://unix.stackexchange.com/a/1919), there are two (potential) problems with this approach:
 - if `key_path` is empty, the files won't be read/written from/to the current directory anymore, but from `/`;
 - I'm not sure what the OpenSSL binary will do under Windows if you use paths with a slash in them (Python will handle it, but Windows might blow it). (This mainly affects the validation call.)

It would be a lot nicer if Ansible would have a filter for joining paths, like `os.path.join()` in Python. That should at least fix the first issue :)

**Comment by nwmcsween** [comment]
From a quick test in ps with openssl binary '/' in paths seems to work

**Comment by felixfontein** [comment]
There's a PR for adding a path join filter: https://github.com/ansible/ansible/pull/62713

For the current problem, it might be easier to add a filter plugin locally to this role. IIRC this can be done. I did something similar earlier with test plugins in some Ansible integration tests (https://github.com/ansible/ansible/blob/devel/test/integration/targets/openssl_csr_info/test_plugins/jinja_compatibility.py; integration tests are essentially roles, so it should work similarly for filter plugins).

**Comment by felixfontein** [comment]
I've updated your PR with such a filter plugin. Can you test whether it works for you? A quick test of mine shows me that the way I use the role still works :)

**Comment by nwmcsween** [comment]
Hey thanks, if the filter works it would be great to merge, I currently don't use acme right now as it's relatively low on the internal things todo at work

**Comment by felixfontein** [comment]
I just renewed my certs with this branch, so it seems to work ;-) I'll merge. Thanks a lot for suggesting this and working on it!

**Pull request merged**
